version: "3.9"

services:
  embedding-service:
    build:
      context: ./Embedder
      dockerfile: Dockerfile
    container_name: embedding-service
    ports:
      - "8000:8000"
    volumes:
      - ~/.insightface/models:/root/.insightface/models
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./Embedder/qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: FIndex.Api/Dockerfile
    container_name: findex-api
    ports:
      - "5181:8080"
    depends_on:
      - qdrant
      - embedding-service
    restart: unless-stopped