version: "3.9"

services:
  embedding-service:
    build:
      context: ./Embedder
      dockerfile: Dockerfile
    container_name: embedding-service
    ports:
      - "8001:8000"
    volumes:
      - ~/.insightface/models:/root/.insightface/models
    restart: unless-stopped

  embedder-service:
    build:
      context: .
      dockerfile: Findex.Embedder/Dockerfile
      platforms:
        - linux/amd64
    container_name: embedder-service
    ports:
      - "5443:8080"
    volumes:
      - ./Findex.Embedder/Data:/app/Data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./Embedder/qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Findex.Api/Dockerfile
    container_name: findex-api
    ports:
      - "5181:8080"
    depends_on:
      - qdrant
      - embedding-service
      - embedder-service
    restart: unless-stopped
